### PR TITLE
Update settings.ts

### PR DESCRIPTION
**Pull request by NicusPulcis**
## Checklist
- [ ] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [ ] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by josericardo-fo** [comment]
don't you think it is going to be too large?

**Comment by NicusPulcis** [comment]
if you can edit it, make it so that it's "Priorità Passive" instead. that way we'll be sure it fits

**Comment by NicusPulcis** [comment]
@josericardo-fo

**Review by NicusPulcis — COMMENTED** [review]
italian is ok now with "Priorità Passive"

**Pull request merged**
